### ISSUE TITLE
import

### ISSUE THREAD

**Issue by Sajgoniarz** [Kinvey/angular2-sdk#4]
`import { Kinvey} from 'kinvey-angular2-sdk';`

Cannot find module 'kinvey-angular2-sdk'.

Is this project even alive? Link are dead.

**Comment by thediycoder** [comment]
@Sajgoniarz  This project is alive. We have just not has much time as we would like to devote to the Angular2 SDK. We hope to be able to devote more time very soon. 

To answer your question why the `kinvey-angular2-sdk` can't be found in an Angular2 app is that the `kinvey-angular2-sdk` does not contain a Typescript definitions file. These are required in order for it to be found in a Typescript environment. We love contributions from the community. If you would like to submit a PR with a Typescript definitions file we will review it and accept it if it is satisfactory.

Please take a look at https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html for help creating a Typescript definitions file.

**Comment by Sajgoniarz** [comment]
Oh, so it's quite funny that importing is in readme, while it doesn't works :D

**Comment by alexbainbridge** [comment]
Hi @Sajgoniarz 

How did you get it working?

I am currently using the HTML5 Kinvey library, which kind of works, although because it is outside the Angular 2 scope, needs Zone.run to make the UI update. So takes 5 lines of code where 1 would be sufficient, if it was working how it should. 

I got Angular 2 library from Kinvey working in JS...... but I am using Ionic 2, which is TypeScript not JS, and haven't got that working yet. 

Would love to see some code! (and so would Kinvey, I am sure, as then we could stop asking them for updates for a fix!)

Or I am banking that the latest version of TypeScript (2.1) comes with new capabilities to help JS be incorporated into TypeScript apps, without typings...... so that may fix it also!

Your code / config would be much appreciated

Thanks. Alex
